fix: updated wf, typecheck for useCopyToClipboard

diff --git a/.github/workflows/bnd.yml b/.github/workflows/bnd.yml
--- a/.github/workflows/bnd.yml
+++ b/.github/workflows/bnd.yml
@@ -1,7 +1,8 @@
-# wjdlz/NOTE: ci@1.0.5-20250211
+# wjdlz/NOTE: ci@1.0.5
 name: bnd
 
 on:
+  workflow_dispatch:
   pull_request:
     types: [closed]
   push:
@@ -42,16 +43,18 @@ jobs:
         with:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-      # - name: fork | build
-      #   if: github.event_name == 'pull_request'
-      #   # id: build
-      #   continue-on-error: false
-      #   shell: bash
-      #   run: |
-      #     pnpm build || {
-      #       echo "build failed with exit code $?"
-      #       exit 1
-      #     }
+      - name: fork | build
+        if: github.event_name == 'pull_request'
+        # id: build
+        continue-on-error: false
+        shell: bash
+        run: |
+          cd packages/usehooks-ts
+          pwd
+          pnpm build || {
+            echo "build failed with exit code $?"
+            exit 1
+          }
 
       - name: action | changesets/NPM-release
         uses: vezham/v0xFE-deployer/.github/actions/changesets/release@timeline
